### PR TITLE
Handle HTTP chunking across multi-byte boundaries

### LINKED ISSUE #22: Multi-byte character corruption on chunk boundaries
A customer reported that a question mark symbol is returned in `snippet` or `extracted_snippet.original` in the response from our Google Maps Reviews API sometimes. I was able to reproduce it using our `serpapi` package:

image

[`serpapi` package code](https://gist.github.com/martin-serpapi/da102985c5c8728f52da96d9cc744463)

However, the issue is not reproducible when sending requests to our Google Maps Reviews API directly with `axios`:

image

[`axios` code](https://gist.github.com/martin-serpapi/1e0cad445d18ba2a301638ccfddf0166)

[Intercom](https://app.intercom.com/a/inbox/yzck75jr/inbox/shared/all/conversation/102910000060603?view=List)

### PR DESCRIPTION
**Pull request by Freaky**
When a response contains multi-byte UTF-8 characters that cross chunk boundaries, appending the two halves to the intermediate string results in two Unicode Replacement Characters being inserted instead of the two halves being joined.

Use StringDecoder to buffer the partial characters across chunks.

Resolves #22

### CODE REVIEW

File: src/utils.ts [hunk 1]
```diff
@@ -63,15 +64,17 @@ export function execute(
   return new Promise((resolve, reject) => {
     let timer: number;
     const req = https.get(url, (resp) => {
+      const decoder = new StringDecoder("utf8");
```
Comment (zyc9012) [inline src/utils.ts]: Simply adding `resp.setEncoding("utf8");` here should do the job, what do you think?

[Documentation](https://nodejs.org/docs/latest-v7.x/api/stream.html#stream_readable_setencoding_encoding)

**Review by zyc9012 — COMMENTED** [review]
Thank you @Freaky 👍

File: src/utils.ts (hunk 1 above)
Comment (Freaky) [reply src/utils.ts]: That's more like it, thanks @zyc9012!

**Comment by Freaky** [comment]
CI failures look to be a result of https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

Instructing it to use OpenSSL's doesn't appear to help, hmm.

**Comment by zyc9012** [comment]
Thank you @Freaky. I fixed the CI and squashed my commit with yours.
